
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sat Feb 17 22:49:06 GMT-12:00 2018
//----------------------------------------------------

package Analisis;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int cadena = 16;
  public static final int decimal = 15;
  public static final int coma = 7;
  public static final int salto = 20;
  public static final int pot = 13;
  public static final int caracter = 19;
  public static final int bool = 17;
  public static final int menos = 9;
  public static final int resEndIf = 26;
  public static final int menor = 22;
  public static final int resThen = 25;
  public static final int div = 11;
  public static final int igual = 23;
  public static final int EOF = 0;
  public static final int as = 3;
  public static final int resIf = 24;
  public static final int error = 1;
  public static final int dim = 2;
  public static final int entero = 14;
  public static final int resString = 5;
  public static final int mul = 10;
  public static final int mas = 8;
  public static final int puntoComa = 6;
  public static final int mod = 12;
  public static final int resInteger = 4;
  public static final int mayor = 21;
  public static final int iden = 18;
}

