
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sat Mar 31 20:47:58 CST 2018
//----------------------------------------------------

package Analisis;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int bool = 53;
  public static final int resIf = 13;
  public static final int mul = 28;
  public static final int resVoid = 49;
  public static final int resProtected = 36;
  public static final int dosPuntos = 44;
  public static final int mayorq = 20;
  public static final int puntoYcoma = 43;
  public static final int resReturn = 33;
  public static final int resElse = 14;
  public static final int coma = 23;
  public static final int igual = 22;
  public static final int resSwitch = 39;
  public static final int resPrivate = 7;
  public static final int resImport = 35;
  public static final int resLong = 12;
  public static final int caracter = 55;
  public static final int menorIgual = 19;
  public static final int iden = 54;
  public static final int resPublic = 6;
  public static final int menos = 27;
  public static final int EOF = 0;
  public static final int resString = 5;
  public static final int mas = 26;
  public static final int menorq = 18;
  public static final int mayorIgual = 21;
  public static final int error = 1;
  public static final int resClass = 38;
  public static final int resChar = 10;
  public static final int entero = 50;
  public static final int or = 31;
  public static final int resDo = 17;
  public static final int resBoolean = 9;
  public static final int punto = 47;
  public static final int resCase = 40;
  public static final int resBreak = 41;
  public static final int and = 30;
  public static final int not = 32;
  public static final int resInt = 4;
  public static final int parC = 46;
  public static final int parentesisC = 25;
  public static final int resDouble = 11;
  public static final int parA = 45;
  public static final int parentesisA = 24;
  public static final int resFor = 16;
  public static final int corC = 3;
  public static final int resDefault = 42;
  public static final int corA = 2;
  public static final int div = 29;
  public static final int resStatic = 8;
  public static final int resFinal = 37;
  public static final int resWhile = 15;
  public static final int decimal = 51;
  public static final int modulo = 48;
  public static final int cadena = 52;
  public static final int resObject = 34;
}

