
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Tue Mar 27 14:09:15 CST 2018
//----------------------------------------------------

package Analisis;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int dim = 5;
  public static final int bool = 58;
  public static final int resIf = 21;
  public static final int mul = 45;
  public static final int module = 9;
  public static final int exit = 33;
  public static final int next = 28;
  public static final int main = 4;
  public static final int mayorq = 36;
  public static final int as = 6;
  public static final int resReturn = 53;
  public static final int Comentario2 = 62;
  public static final int Comentario1 = 61;
  public static final int resElse = 23;
  public static final int coma = 40;
  public static final int crl = 19;
  public static final int igual = 39;
  public static final int resThen = 22;
  public static final int resInteger = 7;
  public static final int resPrivate = 12;
  public static final int resLong = 17;
  public static final int caracter = 60;
  public static final int menorIgual = 35;
  public static final int end = 10;
  public static final int resTo = 26;
  public static final int func = 52;
  public static final int byval = 51;
  public static final int iden = 59;
  public static final int resElseIf = 54;
  public static final int resPublic = 11;
  public static final int menos = 44;
  public static final int sub = 20;
  public static final int EOF = 0;
  public static final int resString = 8;
  public static final int mas = 43;
  public static final int mayorIgual = 37;
  public static final int menorq = 34;
  public static final int error = 1;
  public static final int resChar = 15;
  public static final int cwl = 18;
  public static final int entero = 55;
  public static final int or = 48;
  public static final int resDo = 29;
  public static final int resBoolean = 14;
  public static final int resCase = 32;
  public static final int step = 27;
  public static final int menorMayor = 38;
  public static final int not = 49;
  public static final int and = 47;
  public static final int select = 31;
  public static final int loopUntil = 30;
  public static final int parentesisC = 42;
  public static final int resDouble = 16;
  public static final int parentesisA = 41;
  public static final int resFor = 25;
  public static final int corC = 3;
  public static final int corA = 2;
  public static final int div = 46;
  public static final int and2 = 50;
  public static final int resStatic = 13;
  public static final int resWhile = 24;
  public static final int decimal = 56;
  public static final int cadena = 57;
}

